name: personal_image_gallery_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  image_picker: ^0.8.7+3
  image_cropper: ^9.1.0
  lottie: ^2.7.0
  animated_reorderable_list: ^1.3.0
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  fluttertoast: ^8.2.2
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/icons/


  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
          weight: 400 
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
